// #include <iostream> 
// using namespace std;
// int main()

// {
//     int a = 123;
//     cout << a <<endl;

//     char b = 'v';     //char is use to store single charachter 'ab' ye galat hai
// cout <<b <<endl;

//   bool bl = true ;
//   cout << bl <<endl;

//   float f = 1.2;
//   cout << f <<endl;

//   double d = 1.22333;
//   cout << d <<endl;

//   int size = sizeof(a);
//   cout << "size of a is" << size << endl;
// }



// // #########TYPECASTING

// #include <iostream>
// using namespace std ;
// int main()
// {

// int a = 'a';
// cout << a << endl;

// char ch1 =1234564;
// cout <<ch1<<endl;
// }



// @@@@@@@@@@@@@@@@@@@oprators


//  #include <iostream>
//  using namespace std;
//  int main() 
//  {

// int a = 2.0/5;

// cout << a<< endl;
//  }  0


// #include <iostream>
//  using namespace std;
//  int main() 
//  {

// int a = 2.0/5;

// cout << 2.0/5<< endl;
//  } 0.4


// #include <iostream>
//  using namespace std;
//  int main() 
//  {

// float a = 2.0/5;

// cout << a<< endl;
//  }



// #include <iostream>
//  using namespace std;
//  int main() 
//  {

// double a = 2.0/5;

// cout << a<< endl;
//  }




// relational oprators


 
#include <iostream>
 using namespace std;
 int main() {

int a= 3 ,b= 7;
 bool first = (a<b);
cout <<first<<endl;

int a= 3 ,b= 7;
 bool second = (a<b);
cout <<second<<endl;

int a= 3 ,b= 7;
 bool thired = (a<b);
cout <<first<<endl;

int a= 3 ,b= 7;
 bool four = (a<b);
cout <<first<<endl;

int a= 3 ,b= 7;
 bool five = (a<b);
cout <<first<<endl;

int a= 3 ,b= 7;
 bool sixth (a<b);
cout <<first<<endl;


 }
 