// #include <iostream>
// using namespace std;
// int main(){

// int n;
// cin>>n;

// int i=1;

// while(i<=n){


//     int j=1;
//     while (j<=n)
//     {
//         cout<<j;
//     j=j+1;
//     }
//     cout <<endl;
//     i=i+1;
// }
    
// }





// #include <iostream>
// using namespace std;
// int main(){
// int n;
// cin>>n;

// int i=1;
// int count=1;
// while (i<=n)

// {
//     int j=1;
//     while(j<=n)
//     {cout<<count<<"  ";
//         j=j+1;
//         count=count+1;

//     }
//     cout<<endl;
//     i=i+1;
// }




// }


// 6
// 1  2  3  4  5  6  
// 7  8  9  10  11  12
// 13  14  15  16  17  18
// 19  20  21  22  23  24
// 25  26  27  28  29  30  
// 31  32  33  34  35  36


// 🧨🧨🧨🧨🧨🤦‍♂️💕






    
// #include <iostream>
// using namespace std;
// int main(){
    
// int n;
// cin>>n;

// int row=1;

// while(row<=n){

// int col=1;
// while(col<=row){
//     cout<<"*"<<"   ";
//     col=col+1;

// }
// cout<<endl;
// row=row+1;

// }

// }







    
// #include <iostream>
// using namespace std;
// int main(){
 
//  int n;
//  cin>>n;

//  int row=1;
//  while (row<=n){

//     int col=1;
//     while (col<=row){
//         cout<<row<<"  ";
//         col=col+1;
//     }
//     cout<<endl;
//     row=row+1;
//  }

// }

// answer
// 5

// 1  
// 2  2
// 3  3  3
// 4  4  4  4
// 5  5  5  5  5






    
// #include <iostream>
// using namespace std;
// int main(){
 
//  int n;
//  cin>>n;
 
//  int row =1;
//  while (row<=n)
//  {
//     int col=1;
//     int value =row;
//     while (col<=row){
//         cout<<value;
//         value =value +1;
// col=col+1;

//     }
//     cout <<endl;
//     row=row+1;
//  }

//  }

// 4

// 1
// 23
// 345
// 4567


 


























//  #include <iostream>
//  using namespace std;
//  int main (){

//     int n;
//     cin>>n;

//     int row =1;
//     while (row<=n){

//         int col=1;

//         while (col<=n){
//             char ch='A' +row-1;
//             cout <<ch;
//             col=col+1;
//         }
//         cout <<endl;
//         row=row+1;

//         {
            
//         }
        
//     }
//  }

//  6
// AAAAAA
// BBBBBB
// CCCCCC
// DDDDDD
// EEEEEE
// FFFFFF





// QUETION%%%%%%%%%%
// abc
// abc
// abc



#include