// #include <iostream>
// using namespace  std;

// int main ()
// {
// cout <<"namaste dunia:-)" <<endl;
// }



// #include <iostream>
// using namespace  std;

// int main ()
// {
// cout <<"namaste dunia:-)" <<'\n';
// }





// #include <iostream>
// using namespace  std;

// int main ()
// {
// cout <<"namaste dunia:-) '\n'" ;
// }





// #include <iostream>
// using namespace  std;

// int main ()
// {
// cout <<"namaste dunia:-) " ;
// cout << "\n";
// }






// #include <iostream>
// using namespace  std;

// int main ()
// {
// cout <<"namaste dunia:-)" <<endl;
// }


// 🤞🤞🎐🎐🎐🧨🧨😑😑😑🤦‍♀️😶👌❤😒😘😘😒😍😍🧨🧨🧨😍😍😒❤😒💕🙌🤦‍♂️🤷‍♂️🤷‍♀️🤦‍♀️👌👌❤👌🙌😍😍😍❤❤❤🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣


